---
name: Package build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docker/'
      - 'k2plus-default/'
  workflow_dispatch:

jobs:
  build:
    name: Binary build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Building Binaries
        run: |
          ./build.sh

      - name: Create release and upload artifacts
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          removeArtifacts: true
          allowUpdates: true
          generateReleaseNotes: true
          prerelease: true
          tag: dev-main
          commit: ${{ env.GITHUB_SHA }}
          name: "latest dev pre-release"
          artifacts: "./release/filament-sync-tool_*"
          body: |
            pre-release build  
            --------------------------------------  
            Use the base folder for local filament lookup
